### ISSUE TITLE
[MOBILE] Logo and Dark Mode toggle conflict

### ISSUE THREAD

**Issue by CNKommander** [elites-conflict-mod/ecm-documentation#1]
On mobile, the Logo currently overlaps the Dark Mode toggle button making it hard to see.

![mobileUIissue](https://user-images.githubusercontent.com/33795252/221765425-78c1e755-4f51-4e35-ab16-866ca5cf46f0.png)

**Comment by sanick2** [comment]
Will be addressed when fully migrated to Starlight. See #3
